title: Donghe Chen's Homepage
page-top-title: Donghe Chen
top-section-bg-text: Aerospace
home-subtitle: Donghe Chen, 陈东和 | MBTI: ESTJ | Hometown: Fujian Zhenghe
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'

